# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chembl',
            name='chembl_id',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='ChEMBL ID'),
        ),
    ]
