# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0004_auto_20161103_0655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='herb',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='keggpathway',
            old_name='img',
            new_name='image',
        ),
        migrations.AddField(
            model_name='compound',
            name='describe',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='herb',
            name='describe',
            field=models.TextField(blank=True),
        ),
    ]
