# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0005_auto_20161114_0501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compound',
            name='cid',
        ),
        migrations.AddField(
            model_name='cas',
            name='Compounds',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cas', to='compounds.Compound'),
        ),
        migrations.AddField(
            model_name='chembl',
            name='compounds',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chembl', to='compounds.Compound'),
        ),
        migrations.AddField(
            model_name='cid',
            name='compounds',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cid', to='compounds.Compound'),
        ),
        migrations.AddField(
            model_name='compound',
            name='related_compounds',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compounds.Compound'),
        ),
    ]
