# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0009_auto_20161114_0649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compound',
            name='related_compound',
        ),
        migrations.AddField(
            model_name='compound',
            name='related_compounds',
            field=models.ManyToManyField(related_name='_compound_related_compounds_+', to='compounds.Compound'),
        ),
    ]
