# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0010_auto_20161114_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='instruction',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='main_prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compounds.Prescription'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='modern_usage',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='modern_usage_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='tradition_usage',
            field=models.TextField(blank=True),
        ),
    ]
