# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0011_auto_20161115_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChineseIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=1024)),
                ('pinyin', models.CharField(blank=True, max_length=1024)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnglishIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=1024)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='compound',
            name='chinese_name',
        ),
        migrations.RemoveField(
            model_name='compound',
            name='describe',
        ),
        migrations.RemoveField(
            model_name='compound',
            name='english_name',
        ),
        migrations.RemoveField(
            model_name='compound',
            name='phonetic_name',
        ),
        migrations.RemoveField(
            model_name='compound',
            name='synonyms',
        ),
        migrations.AddField(
            model_name='englishidentity',
            name='compound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compounds.Compound'),
        ),
        migrations.AddField(
            model_name='chineseidentity',
            name='compound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compounds.Compound'),
        ),
    ]
