# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0012_auto_20161128_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='related_compounds',
            field=models.ManyToManyField(blank=True, related_name='_compound_related_compounds_+', to='compounds.Compound'),
        ),
    ]
