# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0014_auto_20161202_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
