# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 07:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0015_auto_20161202_0712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cas',
            old_name='Compounds',
            new_name='compounds',
        ),
    ]
