# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0016_auto_20161202_0752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cas',
            old_name='compounds',
            new_name='compound',
        ),
        migrations.RenameField(
            model_name='chembl',
            old_name='compounds',
            new_name='compound',
        ),
        migrations.RenameField(
            model_name='cid',
            old_name='compounds',
            new_name='compound',
        ),
    ]
