# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 02:46
from __future__ import unicode_literals

from django.db import migrations, models
import django_rdkit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0017_auto_20161202_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compound',
            name='structure',
        ),
        migrations.RemoveField(
            model_name='tcmtaxonomy',
            name='name_class',
        ),
        migrations.RemoveField(
            model_name='tcmtaxonomy',
            name='unique_name',
        ),
        migrations.AddField(
            model_name='compound',
            name='alogp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Calculated ALogP'),
        ),
        migrations.AddField(
            model_name='compound',
            name='bfp',
            field=django_rdkit.models.fields.BfpField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='chinese_name',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='compound',
            name='english_name',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='compound',
            name='formula',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='compound',
            name='hba',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Number hydrogen bond acceptors'),
        ),
        migrations.AddField(
            model_name='compound',
            name='hbd',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Number hydrogen bond donors'),
        ),
        migrations.AddField(
            model_name='compound',
            name='mol',
            field=django_rdkit.models.fields.MolField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='mol_block',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='mol_file',
            field=models.FileField(blank=True, null=True, upload_to='mol_files/'),
        ),
        migrations.AddField(
            model_name='compound',
            name='mol_image',
            field=models.ImageField(blank=True, null=True, upload_to='mol_images/'),
        ),
        migrations.AddField(
            model_name='compound',
            name='mol_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='psa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Polar surface area'),
        ),
        migrations.AddField(
            model_name='compound',
            name='rtb',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Number rotatable bonds'),
        ),
        migrations.AddField(
            model_name='compound',
            name='smiles',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='herb',
            name='related_herbs',
            field=models.ManyToManyField(blank=True, related_name='_herb_related_herbs_+', to='compounds.Herb'),
        ),
        migrations.DeleteModel(
            name='Structure',
        ),
    ]
