# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 02:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0018_auto_20161208_0246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='describe',
            new_name='fangjie',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='instruction',
            new_name='zucheng',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='prescription_text',
        ),
    ]
