# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0019_auto_20161213_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='yongfa',
            field=models.TextField(blank=True),
        ),
    ]
